use yaftekun;

INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(1,'ALDOSIVI',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/aldosivi.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(2,'ARGENTINOS JUNIORS',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/argentinos_juniors.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(3,'ARSENAL',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/arsenal.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(4,'ATLÉTICO RAFAELA',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/atletico_rafaela.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(5,'ATLÉTICO TUCUMÁN',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/atletico_tucuman.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(6,'BANFIELD',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/banfield.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(7,'BELGRANO',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/belgrano.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(8,'BOCA JUNIORS',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/boca_juniors.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(9,'COLÓN',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/colon.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(10,'DEFENSA Y JUSTICIA',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/defensa_y_justicia.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(11,'ESTUDIANTES',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/estudiantes.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(12,'GIMNASIA LA PLATA',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/gimnasia_la_plata.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(13,'GODOY CRUZ',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/godoy_cruz.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(14,'HURACÁN',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/huracan.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(15,'INDEPENDIENTE',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/independiente.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(16,'LANÚS',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/lanus.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(17,'NEWELL\'S OLD BOYS',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/newls_old_boys.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(18,'OLIMPO',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/olimpo.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(19,'PATRONATO',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/patronato.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(20,'QUILMES',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/quilmes.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(21,'RACING CLUB',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/racing_club.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(22,'RIVER PLATE',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/river.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(23,'ROSARIO CENTRAL',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/rosario.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(24,'SAN LORENZO',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/san_lorenzo.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(25,'SAN MARTÍN SAN JUAN',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/san_martin_san_juan.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(26,'SARMIENTO',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/sarmiento.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(27,'TEMPERLEY',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/temperley.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(28,'TIGRE',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/tigre.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(29,'UNIÓN SANTA FE',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/union_santa_fe.png'));
INSERT INTO yaftekun.equipo (idequipo,nombre,imagen)VALUES(30,'VÉLEZ SARSFIELD',load_file('C:/Bitnami/wampstack-5.6.19-0/apps/yaftekun/db/imágenes/velez.png'));
